### ISSUE TITLE
Pseudocode program design for the user matching based on the Hopcroft-Karp algorithm

### ISSUE THREAD

**Issue by fmshja** [fmshja/SEP-2---G16-Project#3]

**Comment by MMetsoila** [comment]
A lot of the pseudocode has been by now written, although I can't yet be sure of it's correctness.

There are few things that still need to be implemented however:

- [ ] In the function `form_groups`: Make a better system for splitting matchings into the groups, by using the variable `matchings_inverse`
- [ ] In the function `form_groups`: Check for repeats of the old groups and create different groups instead
    - This should be done after the new group splitting part (described above) is done
- [ ] In the function `calculate_group_spots`: Implement the last part of the group slot allocation. which ensures that the group size will obey the group size parameters

Each of these have a TODO comment associated with them at the place in the pseudocode where they should be added.
